version: "3.7"
services:
  app:
    build:
      args:
        user: opc
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: diskopum
    container_name: diskopum-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - diskopum

  nginx:
    image: nginx:alpine
    container_name: diskopum-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - diskopum

networks:
  diskopum:
    driver: bridge
